### ISSUE TITLE
Bug z kategoriami

### ISSUE THREAD

**Issue by w33z** [grupa35/pz-mobile#5]
Podkategorie wyświetlają sie podwójnie,. To u nas czy taki burdel na backendzie? xd

**Comment by osinskimarcin** [comment]
tak bekent zrobił xd jak wczoraj sprawdzałem co przychodzi w jsonie to tak było xd

**Comment by rotkom** [comment]
Dlaczego jak jest problem nie informujecie nas o tym? 
Bug był spowodowany złym sposobem zapisywania kategorii. Już działa
